#!/bin/bash

# Check if at least 3 parameters are passed
if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# Use scp to transfer the file with StrictHostKeyChecking disabled
scp -i "${PATH_TO_SSH_KEY}" -o StrictHostKeyChecking=no "${PATH_TO_FILE}" "${USERNAME}@${IP}:~/"

